---
- name: Pull Docker Image
  hosts: ubuntu18
  remote_user: shubh
  tasks:
    - name: Pull Calculator Image from Docker Hub
      docker_image:
        name: shubhverma/calculator_dev_ops_spe
        source: pull